﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MLModel_Webapi
{
    public partial class MLModel
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"UpperBackDistance", @"UpperBackDistance"),new InputOutputColumnPair(@"LegDistance", @"LegDistance"),new InputOutputColumnPair(@"PressureSensor1", @"PressureSensor1"),new InputOutputColumnPair(@"PressureSensor2", @"PressureSensor2"),new InputOutputColumnPair(@"PressureSensor3", @"PressureSensor3")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"UpperBackDistance",@"LegDistance",@"PressureSensor1",@"PressureSensor2",@"PressureSensor3"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Good",inputColumnName:@"Good"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LightGbm(new LightGbmMulticlassTrainer.Options(){NumberOfLeaves=4,NumberOfIterations=25,MinimumExampleCountPerLeaf=20,LearningRate=0.999999776672986,LabelColumnName=@"Good",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.999999776672986,FeatureFraction=0.925615862934869,L1Regularization=2E-10,L2Regularization=0.245672811427595},MaximumBinCountPerFeature=92}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
